name: Scrape Audios

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: write

jobs:
  rclone:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
          disable_base64: true
      - name: List audio files in kdrive share
        run: rclone lsjson --include "*.{flac,mp3}"  "lesbarques-audio:Le Barche sélection"
        id: lsjson
      - name: Save audio file list to file
        run: echo '${{ steps.lsjson.outputs.stdout }}' > docs/audios.json
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/audios.json
          git commit -m "Update audio file list [skip ci]"
          git push origin main